version: "3"
services:
  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - cluster.name="docker-cluster"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data:rw
      - esdata:/usr/share/elasticsearch/logs:rw
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail elasticsearch:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 20
    networks:
      - es-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ELASTIC_HOST=elasticsearch
    container_name: music-api
    ports:
      - "8080:8080"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - es-network
    volumes:
      - ./src/main/resources:/app/src/main/resources

volumes:
  esdata:
    driver: local

networks:
  es-network:
    driver: bridge